[build]
  # Set the base directory to navigate to the parent folder.
  base    = "analytics-dashboard-assessment"
  # Specify the directory with the React app to publish.
  publish = "data-to-visualize/build"
  # Define the command to build the React app.
  command = "npm run build"